services:
  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
    environment:
      - MONGODB_URI=mongodb+srv://vaccine-passport:vaccine-passport@cluster0.7vbqt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  frontend:
    build:
      context: ./admin-panel
    ports:
      - "3001:5000"
    environment:
      - REACT_APP_API_URL=http://127.0.0.1:4000/api/  # Use the appropriate URL for API requests
